### ISSUE TITLE
[Errno 13] Permission denied: 'bin/mac'

### ISSUE THREAD

**Issue by mclark4386** [ViperX7/Alpaca-Turbo#70]
Whenever I try to load a model on my M1 Mac I'm getting the error in the subject line. Installed as prescribed and using python 3.10.10.

**Comment by ViperX7** [comment]
Fixed in new release

**Comment by mclark4386** [comment]
I'm actually still getting it with the latest main branch. Is there a better branch to use?
